name: GitHub Actions Demo Follow Along
on: push
jobs:
#  ___  _    __ ___  ___             
# |  _>| |  / /|  _>| . \            
# | <__| | / / | <__| | |            
# `___/|_|/_/  `___/|___/            
                                   
#  ___           _       _           
# |_ _|_ _  ___ <_>._ _ <_>._ _  ___ 
#  | || '_><_> || || ' || || ' |/ . |
#  |_||_|  <___||_||_|_||_||_|_|\_. |
#                               <___'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Dependencies
        run: npm i

      - name: Build the code
        run: npm run build
